"""Job recommendations: explained, per-candidate recommendations from discovered jobs.

Revision ID: 0013
Revises: 0012
Create Date: 2026-09-30 18:33:29.780267
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0013"
down_revision: str | None = "0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_recommendations",
        sa.Column("candidate_profile_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("source_identifier", sa.String(length=200), nullable=False),
        sa.Column("posting", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "new", "saved", "ignored", name="recommendationstatus", native_enum=False, length=32
            ),
            server_default="new",
            nullable=False,
        ),
        sa.Column("eligible", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "exclusions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "concerns",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("explanation", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("required_coverage", sa.Float(), nullable=True),
        sa.Column("overall_coverage", sa.Float(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=True),
        sa.Column("inputs_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('new', 'saved', 'ignored')", name=op.f("ck_job_recommendations_status_enum")
        ),
        sa.ForeignKeyConstraint(
            ["candidate_profile_id"],
            ["candidate_profiles.id"],
            name=op.f("fk_job_recommendations_candidate_profile_id_candidate_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_job_recommendations_job_id_jobs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_recommendations")),
        sa.UniqueConstraint(
            "candidate_profile_id",
            "source",
            "source_identifier",
            name=op.f("uq_job_recommendations_candidate_profile_id"),
        ),
    )
    op.create_index(
        op.f("ix_job_recommendations_job_id"), "job_recommendations", ["job_id"], unique=False
    )
    op.create_index(
        "ix_job_recommendations_profile_status",
        "job_recommendations",
        ["candidate_profile_id", "status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_job_recommendations_profile_status", table_name="job_recommendations")
    op.drop_index(op.f("ix_job_recommendations_job_id"), table_name="job_recommendations")
    op.drop_table("job_recommendations")
    # ### end Alembic commands ###
