"""Human-in-the-loop approval: approval state, approvals, audit events.

Existing approvals predate the explicit, content-bound approval: they are withdrawn
(back to ready for review) so the candidate approves the current content again.
Submitted applications keep their submission and record the candidate as the reviewer.

Revision ID: 0016
Revises: 0015
Create Date: 2026-10-01 09:55:54.738058
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0016"
down_revision: str | None = "0015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_approvals",
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("reviewer_id", sa.Uuid(), nullable=False),
        sa.Column(
            "decision",
            sa.Enum("approved", "rejected", name="approvaldecision", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision IN ('approved', 'rejected')",
            name=op.f("ck_application_approvals_decision_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_application_approvals_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_id"],
            ["users.id"],
            name=op.f("fk_application_approvals_reviewer_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_approvals")),
        sa.UniqueConstraint(
            "application_id", "version", name=op.f("uq_application_approvals_application_id")
        ),
    )
    op.create_index(
        op.f("ix_application_approvals_reviewer_id"),
        "application_approvals",
        ["reviewer_id"],
        unique=False,
    )
    op.create_table(
        "application_audit_events",
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column(
            "actor",
            sa.Enum(
                "user", "system", "automation", name="statusactor", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor IN ('user', 'system', 'automation')",
            name=op.f("ck_application_audit_events_actor_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_application_audit_events_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_application_audit_events_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_audit_events")),
    )
    op.create_index(
        "ix_application_audit_events_app_created",
        "application_audit_events",
        ["application_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_audit_events_user_id"),
        "application_audit_events",
        ["user_id"],
        unique=False,
    )
    op.add_column(
        "applications",
        sa.Column(
            "approval_state",
            sa.Enum(
                "draft",
                "ready_for_review",
                "approved",
                "rejected",
                "submitted",
                name="approvalstate",
                native_enum=False,
                length=32,
            ),
            server_default="draft",
            nullable=False,
        ),
    )
    op.add_column("applications", sa.Column("approved_by_id", sa.Uuid(), nullable=True))
    op.add_column(
        "applications", sa.Column("approved_content_hash", sa.String(length=64), nullable=True)
    )
    op.create_index(
        op.f("ix_applications_approved_by_id"), "applications", ["approved_by_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_applications_approved_by_id_users"),
        "applications",
        "users",
        ["approved_by_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.execute(
        """
        UPDATE applications AS a SET approved_by_id = p.user_id, approval_state = 'submitted'
        FROM candidate_profiles AS p
        WHERE p.id = a.candidate_profile_id AND a.submitted_at IS NOT NULL
        """
    )
    op.execute(
        """
        UPDATE applications SET approval_state = 'ready_for_review', approved_at = NULL
        WHERE submitted_at IS NULL AND approved_at IS NOT NULL
        """
    )
    op.create_check_constraint(
        op.f("ck_applications_approval_state_enum"),
        "applications",
        "approval_state IN ('draft', 'ready_for_review', 'approved', 'rejected', 'submitted')",
    )
    op.create_check_constraint(
        op.f("ck_applications_approval_recorded"),
        "applications",
        "approval_state <> 'approved' OR (approved_at IS NOT NULL "
        "AND approved_by_id IS NOT NULL AND approved_content_hash IS NOT NULL)",
    )
    op.create_check_constraint(
        op.f("ck_applications_unapproved_has_no_approval"),
        "applications",
        "approval_state NOT IN ('draft', 'ready_for_review', 'rejected') "
        "OR (approved_at IS NULL AND submitted_at IS NULL)",
    )
    op.create_check_constraint(
        op.f("ck_applications_submitted_state_matches"),
        "applications",
        "(approval_state = 'submitted') = (submitted_at IS NOT NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    for name in (
        "ck_applications_submitted_state_matches",
        "ck_applications_unapproved_has_no_approval",
        "ck_applications_approval_recorded",
        "ck_applications_approval_state_enum",
    ):
        op.drop_constraint(op.f(name), "applications", type_="check")
    op.drop_constraint(
        op.f("fk_applications_approved_by_id_users"), "applications", type_="foreignkey"
    )
    op.drop_index(op.f("ix_applications_approved_by_id"), table_name="applications")
    op.drop_column("applications", "approved_content_hash")
    op.drop_column("applications", "approved_by_id")
    op.drop_column("applications", "approval_state")
    op.drop_index(
        op.f("ix_application_audit_events_user_id"), table_name="application_audit_events"
    )
    op.drop_index("ix_application_audit_events_app_created", table_name="application_audit_events")
    op.drop_table("application_audit_events")
    op.drop_index(op.f("ix_application_approvals_reviewer_id"), table_name="application_approvals")
    op.drop_table("application_approvals")
    # ### end Alembic commands ###
