"""Resume ingestion provenance: link suggestions to uploads; record parser output.

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-30 12:57:32.114350
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("profile_suggestions", sa.Column("resume_id", sa.Uuid(), nullable=True))
    op.add_column("profile_suggestions", sa.Column("source_excerpt", sa.Text(), nullable=True))
    op.add_column(
        "profile_suggestions",
        sa.Column("accepted_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.create_index(
        op.f("ix_profile_suggestions_resume_id"), "profile_suggestions", ["resume_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_profile_suggestions_resume_id_resumes"),
        "profile_suggestions",
        "resumes",
        ["resume_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("resumes", sa.Column("parser_name", sa.String(length=50), nullable=True))
    op.add_column(
        "resumes",
        sa.Column(
            "parse_warnings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resumes", "parse_warnings")
    op.drop_column("resumes", "parser_name")
    op.drop_constraint(
        op.f("fk_profile_suggestions_resume_id_resumes"), "profile_suggestions", type_="foreignkey"
    )
    op.drop_index(op.f("ix_profile_suggestions_resume_id"), table_name="profile_suggestions")
    op.drop_column("profile_suggestions", "accepted_data")
    op.drop_column("profile_suggestions", "source_excerpt")
    op.drop_column("profile_suggestions", "resume_id")
    # ### end Alembic commands ###
