"""Application answers: answers to application questions, verified like documents.

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-30 16:44:03.365734
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_answers",
        sa.Column("candidate_profile_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum(
                "motivation",
                "fit",
                "project",
                "skill",
                "experience",
                "behavioral",
                "other",
                name="questiontype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("focus", sa.String(length=100), nullable=True),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_words", sa.Integer(), nullable=True),
        sa.Column("answer", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "verification_failed",
                "verified",
                "approved",
                "archived",
                name="documentstatus",
                native_enum=False,
                length=32,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("generator_name", sa.String(length=50), nullable=True),
        sa.Column(
            "notes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("ai_execution_log_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "question_type IN ('motivation', 'fit', 'project', 'skill', 'experience', 'behavioral', 'other')",
            name=op.f("ck_application_answers_question_type_enum"),
        ),
        sa.CheckConstraint(
            "status <> 'approved' OR approved_at IS NOT NULL",
            name=op.f("ck_application_answers_approved_has_timestamp"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'verification_failed', 'verified', 'approved', 'archived')",
            name=op.f("ck_application_answers_status_enum"),
        ),
        sa.CheckConstraint(
            "length(btrim(question)) > 0", name=op.f("ck_application_answers_question_not_blank")
        ),
        sa.CheckConstraint(
            "max_words IS NULL OR max_words BETWEEN 20 AND 1000",
            name=op.f("ck_application_answers_max_words_range"),
        ),
        sa.ForeignKeyConstraint(
            ["ai_execution_log_id"],
            ["ai_execution_logs.id"],
            name=op.f("fk_application_answers_ai_execution_log_id_ai_execution_logs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["candidate_profile_id"],
            ["candidate_profiles.id"],
            name=op.f("fk_application_answers_candidate_profile_id_candidate_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_application_answers_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_answers")),
    )
    op.create_index(
        op.f("ix_application_answers_ai_execution_log_id"),
        "application_answers",
        ["ai_execution_log_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_answers_job_id"), "application_answers", ["job_id"], unique=False
    )
    op.create_index(
        "ix_application_answers_profile_job",
        "application_answers",
        ["candidate_profile_id", "job_id", "position"],
        unique=False,
    )
    op.add_column("generated_claims", sa.Column("application_answer_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_generated_claims_application_answer_id"),
        "generated_claims",
        ["application_answer_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_generated_claims_application_answer_id_application_answers"),
        "generated_claims",
        "application_answers",
        ["application_answer_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "verification_reports", sa.Column("application_answer_id", sa.Uuid(), nullable=True)
    )
    op.create_index(
        op.f("ix_verification_reports_application_answer_id"),
        "verification_reports",
        ["application_answer_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_verification_reports_application_answer_id_application_answers"),
        "verification_reports",
        "application_answers",
        ["application_answer_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###

    # --- Hand-written: autogenerate doesn't compare CHECK constraints. ---
    # The approved-timestamp check on cover_letters was created under the tailored_resumes
    # name (one shared constraint object); give it its own name.
    op.execute(
        "ALTER TABLE cover_letters RENAME CONSTRAINT ck_tailored_resumes_approved_has_timestamp "
        "TO ck_cover_letters_approved_has_timestamp"
    )
    # AI calls for application answers get their own operation.
    op.drop_constraint(op.f("ck_ai_execution_logs_operation_enum"), "ai_execution_logs", "check")
    op.create_check_constraint(
        op.f("ck_ai_execution_logs_operation_enum"),
        "ai_execution_logs",
        "operation IN ('resume_parsing', 'evidence_extraction', 'job_analysis', 'embedding', 'matching', 'skill_gap_analysis', 'resume_generation', 'cover_letter_generation', 'application_answer', 'claim_verification', 'other')",
    )
    # Claims and reports can now belong to an application answer.
    for table in ("generated_claims", "verification_reports"):
        op.drop_constraint(op.f(f"ck_{table}_exactly_one_document"), table, type_="check")
        op.create_check_constraint(
            op.f(f"ck_{table}_exactly_one_document"),
            table,
            "num_nonnulls(tailored_resume_id, cover_letter_id, application_answer_id) = 1",
        )
    op.drop_constraint(op.f("ck_verification_reports_trigger_enum"), "verification_reports", "check")
    op.create_check_constraint(
        op.f("ck_verification_reports_trigger_enum"),
        "verification_reports",
        "trigger IN ('generation', 'edit', 'manual', 'approval')",
    )


def downgrade() -> None:
    # --- Hand-written (reverse of the CHECK changes above). ---
    op.execute("UPDATE ai_execution_logs SET operation = 'other' WHERE operation = 'application_answer'")
    op.drop_constraint(op.f("ck_ai_execution_logs_operation_enum"), "ai_execution_logs", "check")
    op.create_check_constraint(
        op.f("ck_ai_execution_logs_operation_enum"),
        "ai_execution_logs",
        "operation IN ('resume_parsing', 'evidence_extraction', 'job_analysis', 'embedding', 'matching', 'skill_gap_analysis', 'resume_generation', 'cover_letter_generation', 'claim_verification', 'other')",
    )
    op.execute("DELETE FROM verification_reports WHERE application_answer_id IS NOT NULL")
    op.execute("DELETE FROM generated_claims WHERE application_answer_id IS NOT NULL")
    op.drop_constraint(op.f("ck_verification_reports_trigger_enum"), "verification_reports", "check")
    op.execute("DELETE FROM verification_reports WHERE trigger = 'approval'")
    op.create_check_constraint(
        op.f("ck_verification_reports_trigger_enum"),
        "verification_reports",
        "trigger IN ('generation', 'edit', 'manual')",
    )
    for table in ("generated_claims", "verification_reports"):
        op.drop_constraint(op.f(f"ck_{table}_exactly_one_document"), table, type_="check")
        op.create_check_constraint(
            op.f(f"ck_{table}_exactly_one_document"),
            table,
            "num_nonnulls(tailored_resume_id, cover_letter_id) = 1",
        )
    op.execute(
        "ALTER TABLE cover_letters RENAME CONSTRAINT ck_cover_letters_approved_has_timestamp "
        "TO ck_tailored_resumes_approved_has_timestamp"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_verification_reports_application_answer_id_application_answers"),
        "verification_reports",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_verification_reports_application_answer_id"), table_name="verification_reports"
    )
    op.drop_column("verification_reports", "application_answer_id")
    op.drop_constraint(
        op.f("fk_generated_claims_application_answer_id_application_answers"),
        "generated_claims",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_generated_claims_application_answer_id"), table_name="generated_claims")
    op.drop_column("generated_claims", "application_answer_id")
    op.drop_index("ix_application_answers_profile_job", table_name="application_answers")
    op.drop_index(op.f("ix_application_answers_job_id"), table_name="application_answers")
    op.drop_index(
        op.f("ix_application_answers_ai_execution_log_id"), table_name="application_answers"
    )
    op.drop_table("application_answers")
    # ### end Alembic commands ###
