"""Evidence retrieval metadata: generated verification_status, embedded_at.

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-30 13:26:19.954206
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "candidate_evidence",
        sa.Column(
            "verification_status",
            sa.String(length=16),
            sa.Computed(
                "CASE WHEN (confirmed_at IS NOT NULL) THEN 'verified'::text "
                "ELSE 'unverified'::text END",
                persisted=True,
            ),
            nullable=False,
        ),
    )
    op.add_column(
        "candidate_evidence", sa.Column("embedded_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("candidate_evidence", "embedded_at")
    op.drop_column("candidate_evidence", "verification_status")
    # ### end Alembic commands ###
