"""Job analysis: salary/deadline/provenance fields, requirement excerpts, new enum values.

Hand-edited: CHECK constraints for new enum columns and the extended requirement_type /
importance values are written explicitly (autogenerate does not handle CHECKs).

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-30 13:47:11.173974
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job_requirements", sa.Column("source_excerpt", sa.Text(), nullable=True))
    op.add_column(
        "jobs",
        sa.Column(
            "salary_period",
            sa.Enum(
                "hour",
                "day",
                "week",
                "month",
                "year",
                name="salaryperiod",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
    )
    op.add_column("jobs", sa.Column("salary_text", sa.Text(), nullable=True))
    op.add_column("jobs", sa.Column("application_deadline", sa.Date(), nullable=True))
    op.add_column(
        "jobs",
        sa.Column(
            "input_method",
            sa.Enum(
                "pasted_text", "manual_entry", name="jobinputmethod", native_enum=False, length=32
            ),
            nullable=True,
        ),
    )
    op.add_column("jobs", sa.Column("analyzer_name", sa.String(length=50), nullable=True))
    op.add_column(
        "jobs",
        sa.Column(
            "analysis_warnings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column("jobs", sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=True))
    op.alter_column("jobs", "description", existing_type=sa.TEXT(), nullable=True)
    op.create_check_constraint(
        op.f("ck_jobs_salary_period_enum"), "jobs",
        "salary_period IN ('hour', 'day', 'week', 'month', 'year')",
    )
    op.create_check_constraint(
        op.f("ck_jobs_input_method_enum"), "jobs",
        "input_method IN ('pasted_text', 'manual_entry')",
    )
    _set_check("requirement_type", NEW_TYPES)
    _set_check("importance", NEW_IMPORTANCE)
    # ### end Alembic commands ###


OLD_TYPES = ("skill", "experience", "education", "certification", "language", "responsibility",
             "other")
NEW_TYPES = ("skill", "technology", "experience", "education", "certification", "language",
             "eligibility", "responsibility", "other")
OLD_IMPORTANCE = ("required", "preferred")
NEW_IMPORTANCE = ("required", "preferred", "informational")


def _set_check(column: str, values: tuple[str, ...]) -> None:
    name = op.f(f"ck_job_requirements_{column}_enum")
    op.drop_constraint(name, "job_requirements", type_="check")
    allowed = ", ".join(f"'{v}'" for v in values)
    op.create_check_constraint(name, "job_requirements", f"{column} IN ({allowed})")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "DELETE FROM job_requirements WHERE requirement_type IN ('technology', 'eligibility') "
        "OR importance = 'informational'"
    )
    _set_check("importance", OLD_IMPORTANCE)
    _set_check("requirement_type", OLD_TYPES)
    op.execute("UPDATE jobs SET description = '' WHERE description IS NULL")
    op.alter_column("jobs", "description", existing_type=sa.TEXT(), nullable=False)
    op.drop_column("jobs", "analyzed_at")
    op.drop_column("jobs", "analysis_warnings")
    op.drop_column("jobs", "analyzer_name")
    op.drop_column("jobs", "input_method")
    op.drop_column("jobs", "application_deadline")
    op.drop_column("jobs", "salary_text")
    op.drop_column("jobs", "salary_period")
    op.drop_column("job_requirements", "source_excerpt")
    # ### end Alembic commands ###
