"""Profile job-search preferences and AI profile suggestions.

Hand-edited after autogenerate: target_roles is renamed (not dropped), and CHECK constraints
for new enum columns and the extended evidence origin are added explicitly (add_column does
not create table-level constraints, and autogenerate does not detect CHECK changes).

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-30 12:30:13.708033
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile_suggestions",
        sa.Column("candidate_profile_id", sa.Uuid(), nullable=False),
        sa.Column(
            "section",
            sa.Enum(
                "personal_info",
                "education",
                "work_experience",
                "project",
                "certification",
                "achievement",
                "coursework",
                "skill",
                "evidence",
                name="suggestionsection",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "action",
            sa.Enum("create", "update", name="suggestionaction", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("proposed_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "source",
            sa.Enum(
                "resume_extraction",
                "ai_generation",
                name="suggestionsource",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "accepted",
                "rejected",
                name="suggestionstatus",
                native_enum=False,
                length=32,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied_target_id", sa.Uuid(), nullable=True),
        sa.Column("ai_execution_log_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(action = 'update') = (target_id IS NOT NULL) OR section = 'personal_info'",
            name=op.f("ck_profile_suggestions_update_has_target"),
        ),
        sa.CheckConstraint(
            "(status = 'pending') = (reviewed_at IS NULL)",
            name=op.f("ck_profile_suggestions_reviewed_when_decided"),
        ),
        sa.CheckConstraint(
            "action IN ('create', 'update')", name=op.f("ck_profile_suggestions_action_enum")
        ),
        sa.CheckConstraint(
            "section IN ('personal_info', 'education', 'work_experience', 'project', 'certification', 'achievement', 'coursework', 'skill', 'evidence')",
            name=op.f("ck_profile_suggestions_section_enum"),
        ),
        sa.CheckConstraint(
            "source IN ('resume_extraction', 'ai_generation')",
            name=op.f("ck_profile_suggestions_source_enum"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'rejected')",
            name=op.f("ck_profile_suggestions_status_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["ai_execution_log_id"],
            ["ai_execution_logs.id"],
            name=op.f("fk_profile_suggestions_ai_execution_log_id_ai_execution_logs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["candidate_profile_id"],
            ["candidate_profiles.id"],
            name=op.f("fk_profile_suggestions_candidate_profile_id_candidate_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_suggestions")),
    )
    op.create_index(
        op.f("ix_profile_suggestions_ai_execution_log_id"),
        "profile_suggestions",
        ["ai_execution_log_id"],
        unique=False,
    )
    op.create_index(
        "ix_profile_suggestions_profile_status",
        "profile_suggestions",
        ["candidate_profile_id", "status"],
        unique=False,
    )
    op.alter_column("candidate_profiles", "target_roles", new_column_name="preferred_roles")
    op.add_column(
        "candidate_profiles",
        sa.Column(
            "preferred_locations",
            postgresql.ARRAY(sa.String(length=200)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
    )
    op.add_column(
        "candidate_profiles",
        sa.Column(
            "work_modes",
            postgresql.ARRAY(sa.String(length=32)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
    )
    op.add_column(
        "candidate_profiles",
        sa.Column(
            "job_types",
            postgresql.ARRAY(sa.String(length=32)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
    )
    op.add_column(
        "candidate_profiles",
        sa.Column(
            "experience_level",
            sa.Enum(
                "student",
                "entry_level",
                "junior",
                "mid_level",
                "senior",
                "lead",
                name="experiencelevel",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
    )
    op.create_check_constraint(
        op.f("ck_candidate_profiles_work_modes_enum"),
        "candidate_profiles",
        "work_modes <@ ARRAY['onsite', 'hybrid', 'remote']::varchar[]",
    )
    op.create_check_constraint(
        op.f("ck_candidate_profiles_job_types_enum"),
        "candidate_profiles",
        "job_types <@ ARRAY['full_time', 'part_time', 'internship', 'contract', 'freelance', "
        "'volunteer', 'other']::varchar[]",
    )
    op.create_check_constraint(
        op.f("ck_candidate_profiles_experience_level_enum"),
        "candidate_profiles",
        "experience_level IN ('student', 'entry_level', 'junior', 'mid_level', 'senior', 'lead')",
    )
    _replace_origin_check("'user_entered', 'resume_extracted', 'ai_suggested'")
    # Allow percentage GPA scales (100.00).
    for column in ("gpa", "gpa_scale"):
        op.alter_column("educations", column, type_=sa.Numeric(5, 2))


def _replace_origin_check(allowed: str) -> None:
    name = op.f("ck_candidate_evidence_origin_enum")
    op.drop_constraint(name, "candidate_evidence", type_="check")
    op.create_check_constraint(name, "candidate_evidence", f"origin IN ({allowed})")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM candidate_evidence WHERE origin = 'ai_suggested'")
    for column in ("gpa", "gpa_scale"):
        op.alter_column("educations", column, type_=sa.Numeric(4, 2))
    _replace_origin_check("'user_entered', 'resume_extracted'")
    op.drop_column("candidate_profiles", "experience_level")
    op.drop_column("candidate_profiles", "job_types")
    op.drop_column("candidate_profiles", "work_modes")
    op.drop_column("candidate_profiles", "preferred_locations")
    op.alter_column("candidate_profiles", "preferred_roles", new_column_name="target_roles")
    op.drop_index("ix_profile_suggestions_profile_status", table_name="profile_suggestions")
    op.drop_index(
        op.f("ix_profile_suggestions_ai_execution_log_id"), table_name="profile_suggestions"
    )
    op.drop_table("profile_suggestions")
    # ### end Alembic commands ###
