"""Requirement-level matching: per-requirement assessments, cited evidence, coverage scores.

Hand-edited: range CHECKs for the new job_matches columns (autogenerate misses CHECKs on
existing tables).

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-30 14:12:35.616375
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "requirement_matches",
        sa.Column("job_match_id", sa.Uuid(), nullable=False),
        sa.Column("job_requirement_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "matched",
                "partial",
                "missing",
                "unknown",
                name="matchstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("semantic_similarity", sa.Float(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("judge", sa.String(length=50), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('matched', 'partial', 'missing', 'unknown')",
            name=op.f("ck_requirement_matches_status_enum"),
        ),
        sa.CheckConstraint(
            "semantic_similarity >= -1 AND semantic_similarity <= 1",
            name=op.f("ck_requirement_matches_similarity_range"),
        ),
        sa.ForeignKeyConstraint(
            ["job_match_id"],
            ["job_matches.id"],
            name=op.f("fk_requirement_matches_job_match_id_job_matches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_requirement_id"],
            ["job_requirements.id"],
            name=op.f("fk_requirement_matches_job_requirement_id_job_requirements"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_matches")),
        sa.UniqueConstraint(
            "job_match_id", "job_requirement_id", name=op.f("uq_requirement_matches_job_match_id")
        ),
    )
    op.create_index(
        op.f("ix_requirement_matches_job_requirement_id"),
        "requirement_matches",
        ["job_requirement_id"],
        unique=False,
    )
    op.create_table(
        "requirement_match_evidence",
        sa.Column("requirement_match_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("similarity", sa.Float(), nullable=True),
        sa.Column("rank", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["candidate_evidence.id"],
            name=op.f("fk_requirement_match_evidence_evidence_id_candidate_evidence"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requirement_match_id"],
            ["requirement_matches.id"],
            name=op.f("fk_requirement_match_evidence_requirement_match_id_requirement_matches"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "requirement_match_id", "evidence_id", name=op.f("pk_requirement_match_evidence")
        ),
    )
    op.create_index(
        op.f("ix_requirement_match_evidence_evidence_id"),
        "requirement_match_evidence",
        ["evidence_id"],
        unique=False,
    )
    op.add_column("job_matches", sa.Column("required_coverage", sa.Float(), nullable=True))
    op.add_column("job_matches", sa.Column("preferred_coverage", sa.Float(), nullable=True))
    op.add_column("job_matches", sa.Column("matcher_name", sa.String(length=50), nullable=True))
    op.add_column("job_matches", sa.Column("embedding_model", sa.String(length=100), nullable=True))
    op.add_column(
        "job_matches",
        sa.Column(
            "warnings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.add_column(
        "job_matches", sa.Column("inputs_fingerprint", sa.String(length=64), nullable=True)
    )
    for column in ("required_coverage", "preferred_coverage"):
        op.create_check_constraint(
            op.f(f"ck_job_matches_{column}_range"),
            "job_matches",
            f"{column} >= 0 AND {column} <= 1",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("job_matches", "inputs_fingerprint")
    for column in ("required_coverage", "preferred_coverage"):
        op.drop_constraint(op.f(f"ck_job_matches_{column}_range"), "job_matches", type_="check")
    op.drop_column("job_matches", "warnings")
    op.drop_column("job_matches", "embedding_model")
    op.drop_column("job_matches", "matcher_name")
    op.drop_column("job_matches", "preferred_coverage")
    op.drop_column("job_matches", "required_coverage")
    op.drop_index(
        op.f("ix_requirement_match_evidence_evidence_id"), table_name="requirement_match_evidence"
    )
    op.drop_table("requirement_match_evidence")
    op.drop_index(
        op.f("ix_requirement_matches_job_requirement_id"), table_name="requirement_matches"
    )
    op.drop_table("requirement_matches")
    # ### end Alembic commands ###
