"""Browser-assisted applications: runs and their audit log.

Revision ID: 0015
Revises: 0014
Create Date: 2026-09-30 22:00:45.447382
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0015"
down_revision: str | None = "0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application_runs",
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "preparing",
                "needs_input",
                "awaiting_review",
                "submitting",
                "submitted",
                "stopped",
                "failed",
                "cancelled",
                name="runstatus",
                native_enum=False,
                length=32,
            ),
            server_default="preparing",
            nullable=False,
        ),
        sa.Column("destination_url", sa.Text(), nullable=False),
        sa.Column("adapter", sa.String(length=50), nullable=True),
        sa.Column(
            "inputs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("review", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("review_hash", sa.String(length=64), nullable=True),
        sa.Column(
            "problems",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("stop_reason", sa.Text(), nullable=True),
        sa.Column("prepared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmation_reference", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'submitted' OR (confirmed_at IS NOT NULL AND submitted_at IS NOT NULL AND review_hash IS NOT NULL)",
            name=op.f("ck_application_runs_submitted_requires_confirmation"),
        ),
        sa.CheckConstraint(
            "status IN ('preparing', 'needs_input', 'awaiting_review', 'submitting', 'submitted', 'stopped', 'failed', 'cancelled')",
            name=op.f("ck_application_runs_status_enum"),
        ),
        sa.CheckConstraint(
            "confirmed_at IS NULL OR review_hash IS NOT NULL",
            name=op.f("ck_application_runs_confirmation_needs_review"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_application_runs_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_runs")),
    )
    op.create_index(
        op.f("ix_application_runs_application_id"),
        "application_runs",
        ["application_id"],
        unique=False,
    )
    op.create_table(
        "automation_audit_events",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "actor",
            sa.Enum(
                "user", "system", "automation", name="auditactor", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor IN ('user', 'system', 'automation')",
            name=op.f("ck_automation_audit_events_actor_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["application_runs.id"],
            name=op.f("fk_automation_audit_events_run_id_application_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_automation_audit_events")),
    )
    op.create_index(
        "ix_automation_audit_events_run_created",
        "automation_audit_events",
        ["run_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_automation_audit_events_run_created", table_name="automation_audit_events")
    op.drop_table("automation_audit_events")
    op.drop_index(op.f("ix_application_runs_application_id"), table_name="application_runs")
    op.drop_table("application_runs")
    # ### end Alembic commands ###
