"""Agent orchestration: runs and the agent execution log.

Revision ID: 0017
Revises: 0016
Create Date: 2026-10-01 10:21:45.721393
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0017"
down_revision: str | None = "0016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_runs",
        sa.Column("candidate_profile_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("application_id", sa.Uuid(), nullable=True),
        sa.Column(
            "stage",
            sa.Enum(
                "discover",
                "analyze",
                "match",
                "prepare",
                "verify",
                "review",
                "approve",
                "submit",
                "track",
                "done",
                name="stage",
                native_enum=False,
                length=32,
            ),
            server_default="discover",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "ready",
                "waiting_for_human",
                "completed",
                "failed",
                "cancelled",
                name="runstatus",
                native_enum=False,
                length=32,
            ),
            server_default="ready",
            nullable=False,
        ),
        sa.Column("goal", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "inputs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("pause", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("steps", sa.Integer(), server_default="0", nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(stage = 'done') = (status = 'completed')",
            name=op.f("ck_agent_runs_done_is_completed"),
        ),
        sa.CheckConstraint(
            "(status = 'waiting_for_human') = (pause IS NOT NULL)",
            name=op.f("ck_agent_runs_paused_has_reason"),
        ),
        sa.CheckConstraint(
            "stage IN ('discover', 'analyze', 'match', 'prepare', 'verify', 'review', 'approve', 'submit', 'track', 'done')",
            name=op.f("ck_agent_runs_stage_enum"),
        ),
        sa.CheckConstraint(
            "status IN ('ready', 'waiting_for_human', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_agent_runs_status_enum"),
        ),
        sa.CheckConstraint("steps >= 0", name=op.f("ck_agent_runs_steps_non_negative")),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_agent_runs_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["candidate_profile_id"],
            ["candidate_profiles.id"],
            name=op.f("fk_agent_runs_candidate_profile_id_candidate_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_agent_runs_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_runs")),
    )
    op.create_index(
        op.f("ix_agent_runs_application_id"), "agent_runs", ["application_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_runs_candidate_profile_id"),
        "agent_runs",
        ["candidate_profile_id"],
        unique=False,
    )
    op.create_index(op.f("ix_agent_runs_job_id"), "agent_runs", ["job_id"], unique=False)
    op.create_table(
        "agent_action_logs",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "agent",
            sa.Enum(
                "orchestrator",
                "candidate_profile",
                "job_discovery",
                "job_analysis",
                "matching",
                "resume",
                "cover_letter",
                "claim_verification",
                "application_preparation",
                "human_approval",
                "application_tracking",
                name="agentname",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "stage",
            sa.Enum(
                "discover",
                "analyze",
                "match",
                "prepare",
                "verify",
                "review",
                "approve",
                "submit",
                "track",
                "done",
                name="stage",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("task", sa.String(length=300), nullable=False),
        sa.Column("tool", sa.String(length=100), nullable=False),
        sa.Column("input_summary", sa.Text(), nullable=False),
        sa.Column("output_summary", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "succeeded",
                "skipped",
                "paused",
                "failed",
                name="actionstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "agent IN ('orchestrator', 'candidate_profile', 'job_discovery', 'job_analysis', 'matching', 'resume', 'cover_letter', 'claim_verification', 'application_preparation', 'human_approval', 'application_tracking')",
            name=op.f("ck_agent_action_logs_agent_enum"),
        ),
        sa.CheckConstraint(
            "stage IN ('discover', 'analyze', 'match', 'prepare', 'verify', 'review', 'approve', 'submit', 'track', 'done')",
            name=op.f("ck_agent_action_logs_stage_enum"),
        ),
        sa.CheckConstraint(
            "status IN ('succeeded', 'skipped', 'paused', 'failed')",
            name=op.f("ck_agent_action_logs_status_enum"),
        ),
        sa.CheckConstraint(
            "duration_ms >= 0", name=op.f("ck_agent_action_logs_duration_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["agent_runs.id"],
            name=op.f("fk_agent_action_logs_run_id_agent_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_agent_action_logs")),
    )
    op.create_index(
        "ix_agent_action_logs_run_created",
        "agent_action_logs",
        ["run_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_agent_action_logs_run_created", table_name="agent_action_logs")
    op.drop_table("agent_action_logs")
    op.drop_index(op.f("ix_agent_runs_job_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_candidate_profile_id"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_application_id"), table_name="agent_runs")
    op.drop_table("agent_runs")
    # ### end Alembic commands ###
