"""Structured cover letters: JSON content, generator name and notes.

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-30 16:18:07.820158
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cover_letters", sa.Column("generator_name", sa.String(length=50), nullable=True))
    op.add_column(
        "cover_letters",
        sa.Column(
            "notes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.alter_column(
        "cover_letters",
        "content",
        existing_type=sa.TEXT(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=False,
        # Any earlier plain-text letter is kept as a JSON string.
        postgresql_using="to_jsonb(content)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "cover_letters",
        "content",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.TEXT(),
        existing_nullable=False,
        postgresql_using="content::text",
    )
    op.drop_column("cover_letters", "notes")
    op.drop_column("cover_letters", "generator_name")
    # ### end Alembic commands ###
