"""Application tracker lifecycle: discovered to offer; date discovered.

Revision ID: 0014
Revises: 0013
Create Date: 2026-09-30 20:55:42.104721
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0014"
down_revision: str | None = "0013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

NEW = (
    "discovered", "saved", "analyzed", "application_prepared", "awaiting_approval",
    "submitted", "assessment", "interview", "offer", "rejected", "withdrawn",
)
OLD = (
    "draft", "ready_for_review", "approved", "filling", "awaiting_submission", "submitted",
    "interviewing", "offer", "accepted", "rejected", "withdrawn",
)
NEW_GATED = ("submitted", "assessment", "interview", "offer")
OLD_GATED = (
    "approved", "filling", "awaiting_submission", "submitted", "interviewing", "offer",
    "accepted", "rejected",
)
TO_NEW = """CASE {col}
    WHEN 'draft' THEN 'saved'
    WHEN 'ready_for_review' THEN 'awaiting_approval'
    WHEN 'approved' THEN 'awaiting_approval'
    WHEN 'filling' THEN 'awaiting_approval'
    WHEN 'awaiting_submission' THEN 'awaiting_approval'
    WHEN 'interviewing' THEN 'interview'
    WHEN 'accepted' THEN 'offer'
    ELSE {col} END"""
TO_OLD = """CASE {col}
    WHEN 'discovered' THEN 'draft'
    WHEN 'saved' THEN 'draft'
    WHEN 'analyzed' THEN 'draft'
    WHEN 'application_prepared' THEN 'draft'
    WHEN 'awaiting_approval' THEN 'ready_for_review'
    WHEN 'assessment' THEN 'interviewing'
    WHEN 'interview' THEN 'interviewing'
    ELSE {col} END"""


def _quoted(values: tuple[str, ...]) -> str:
    return ", ".join(f"'{v}'" for v in values)


def _checks(values: tuple[str, ...], gated: tuple[str, ...], submitted: tuple[str, ...]) -> None:
    op.create_check_constraint(
        op.f("ck_applications_status_enum"), "applications", f"status IN ({_quoted(values)})"
    )
    op.create_check_constraint(
        op.f("ck_applications_approval_required"),
        "applications",
        f"status NOT IN ({_quoted(gated)}) OR approved_at IS NOT NULL",
    )
    op.create_check_constraint(
        op.f("ck_applications_submitted_has_time"),
        "applications",
        f"status NOT IN ({_quoted(submitted)}) OR submitted_at IS NOT NULL",
    )
    for column in ("from_status", "to_status"):
        op.create_check_constraint(
            op.f(f"ck_application_status_history_{column}_enum"),
            "application_status_history",
            f"{column} IN ({_quoted(values)})",
        )


def _drop_checks() -> None:
    for name in ("status_enum", "approval_required", "submitted_has_time"):
        op.drop_constraint(op.f(f"ck_applications_{name}"), "applications", "check")
    for column in ("from_status", "to_status"):
        op.drop_constraint(
            op.f(f"ck_application_status_history_{column}_enum"),
            "application_status_history",
            "check",
        )


def _map(case: str) -> None:
    op.execute(f"UPDATE applications SET status = {case.format(col='status')}")
    for column in ("from_status", "to_status"):
        op.execute(
            f"UPDATE application_status_history SET {column} = {case.format(col=column)} "
            f"WHERE {column} IS NOT NULL"
        )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications", sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column(
        "applications",
        "status",
        existing_type=sa.VARCHAR(length=32),
        server_default="saved",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
    # --- Hand-written: the lifecycle's CHECK constraints and data. ---
    _drop_checks()
    _map(TO_NEW)
    _checks(NEW, NEW_GATED, NEW_GATED)


def downgrade() -> None:
    # --- Hand-written (reverse). ---
    _drop_checks()
    _map(TO_OLD)
    # Old approval-gated statuses need approved_at; rows without it fall back to review.
    op.execute(
        "UPDATE applications SET status = 'ready_for_review' "
        f"WHERE approved_at IS NULL AND status IN ({_quoted(OLD_GATED)})"
    )
    _checks(OLD, OLD_GATED, ("submitted",))
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "applications",
        "status",
        existing_type=sa.VARCHAR(length=32),
        server_default=sa.text("'draft'::character varying"),
        existing_nullable=False,
    )
    op.drop_column("applications", "discovered_at")
    # ### end Alembic commands ###
