"""Core schema: profile, evidence, jobs, matching, documents, claims, applications, AI logs.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-30 12:14:37.482399
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skills",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("normalized_name", sa.String(length=100), nullable=False),
        sa.Column(
            "category",
            sa.Enum(
                "programming_language",
                "framework",
                "library",
                "tool",
                "platform",
                "database",
                "cloud",
                "methodology",
                "domain",
                "soft_skill",
                "language",
                "other",
                name="skillcategory",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('programming_language', 'framework', 'library', 'tool', 'platform', 'database', 'cloud', 'methodology', 'domain', 'soft_skill', 'language', 'other')",
            name=op.f("ck_skills_category_enum"),
        ),
        sa.CheckConstraint(
            "normalized_name = lower(btrim(normalized_name)) AND normalized_name <> ''",
            name=op.f("ck_skills_normalized_name_format"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skills")),
        sa.UniqueConstraint("normalized_name", name=op.f("uq_skills_normalized_name")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_users_email_lowercase")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "ai_execution_logs",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "operation",
            sa.Enum(
                "resume_parsing",
                "evidence_extraction",
                "job_analysis",
                "embedding",
                "matching",
                "skill_gap_analysis",
                "resume_generation",
                "cover_letter_generation",
                "claim_verification",
                "other",
                name="aioperation",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_version", sa.String(length=50), nullable=True),
        sa.Column(
            "status",
            sa.Enum("success", "error", name="aiexecutionstatus", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("estimated_cost_usd", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("request_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("response_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "operation IN ('resume_parsing', 'evidence_extraction', 'job_analysis', 'embedding', 'matching', 'skill_gap_analysis', 'resume_generation', 'cover_letter_generation', 'claim_verification', 'other')",
            name=op.f("ck_ai_execution_logs_operation_enum"),
        ),
        sa.CheckConstraint(
            "status <> 'error' OR error_message IS NOT NULL",
            name=op.f("ck_ai_execution_logs_error_has_message"),
        ),
        sa.CheckConstraint(
            "status IN ('success', 'error')", name=op.f("ck_ai_execution_logs_status_enum")
        ),
        sa.CheckConstraint(
            "input_tokens >= 0 AND output_tokens >= 0 AND latency_ms >= 0 AND estimated_cost_usd >= 0",
            name=op.f("ck_ai_execution_logs_non_negative_usage"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_ai_execution_logs_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_execution_logs")),
    )
    op.create_index(
        "ix_ai_execution_logs_operation_created",
        "ai_execution_logs",
        ["operation", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_ai_execution_logs_user_created",
        "ai_execution_logs",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "candidate_profiles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("headline", sa.String(length=300), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("contact_email", sa.String(length=320), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("website_url", sa.Text(), nullable=True),
        sa.Column("linkedin_url", sa.Text(), nullable=True),
        sa.Column("github_url", sa.Text(), nullable=True),
        sa.Column(
            "target_roles",
            postgresql.ARRAY(sa.String(length=200)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_candidate_profiles_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_profiles")),
        sa.UniqueConstraint("user_id", name=op.f("uq_candidate_profiles_user_id")),
    )
    op.create_table(
        "jobs",
        sa.Column(
            "source",
            sa.Enum(
                "manual",
                "job_board_api",
                "ats_api",
                "company_site",
                "feed",
                "other",
                name="jobsource",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("source_name", sa.String(length=100), nullable=True),
        sa.Column("external_id", sa.String(length=200), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("company_name", sa.String(length=300), nullable=False),
        sa.Column("location", sa.String(length=300), nullable=True),
        sa.Column(
            "workplace_type",
            sa.Enum(
                "onsite", "hybrid", "remote", name="workplacetype", native_enum=False, length=32
            ),
            nullable=True,
        ),
        sa.Column(
            "employment_type",
            sa.Enum(
                "full_time",
                "part_time",
                "internship",
                "contract",
                "freelance",
                "volunteer",
                "other",
                name="employmenttype",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("seniority", sa.String(length=100), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("salary_min", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("salary_max", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("salary_currency", sa.String(length=3), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("embedding", Vector(1024), nullable=True),
        sa.Column("embedding_model", sa.String(length=100), nullable=True),
        sa.CheckConstraint(
            "employment_type IN ('full_time', 'part_time', 'internship', 'contract', 'freelance', 'volunteer', 'other')",
            name=op.f("ck_jobs_employment_type_enum"),
        ),
        sa.CheckConstraint(
            "salary_currency ~ '^[A-Z]{3}$'", name=op.f("ck_jobs_salary_currency_iso")
        ),
        sa.CheckConstraint(
            "source IN ('manual', 'job_board_api', 'ats_api', 'company_site', 'feed', 'other')",
            name=op.f("ck_jobs_source_enum"),
        ),
        sa.CheckConstraint(
            "workplace_type IN ('onsite', 'hybrid', 'remote')",
            name=op.f("ck_jobs_workplace_type_enum"),
        ),
        sa.CheckConstraint(
            "salary_min IS NULL OR salary_max IS NULL OR salary_max >= salary_min",
            name=op.f("ck_jobs_salary_range"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_jobs_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("source", "source_name", "external_id", name=op.f("uq_jobs_source")),
    )
    op.create_index("ix_jobs_active_posted", "jobs", ["is_active", "posted_at"], unique=False)
    op.create_index(
        op.f("ix_jobs_created_by_user_id"), "jobs", ["created_by_user_id"], unique=False
    )
    op.create_index(
        "ix_jobs_embedding_hnsw",
        "jobs",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_table(
        "achievements",
        sa.Column("candidate_profile_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("issuer", sa.String(length=200), nullable=True),
        sa.Column("achieved_on", sa.Date(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_profile_id"],
            ["candidate_profiles.id"],
            name=op.f("fk_achievements_candidate_profile_id_candidate_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_achievements")),
    )
    op.create_index(
        op.f("ix_achievements_candidate_profile_id"),
        "achievements",
        ["candidate_profile_id"],
        unique=False,
    )
    op.create_table(
        "candidate_skills",
        sa.Column("candidate_profile_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.Column(
            "proficiency",
            sa.Enum(
                "beginner",
                "intermediate",
                "advanced",
                "expert",
                name="proficiencylevel",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("years_experience", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "proficiency IN ('beginner', 'intermediate', 'advanced', 'expert')",
            name=op.f("ck_candidate_skills_proficiency_enum"),
        ),
        sa.CheckConstraint(
            "years_experience >= 0", name=op.f("ck_candidate_skills_years_experience_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["candidate_profile_id"],
            ["candidate_profiles.id"],
            name=op.f("fk_candidate_skills_candidate_profile_id_candidate_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"], ["skills.id"], name=op.f("fk_candidate_skills_skill_id_skills")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_skills")),
        sa.UniqueConstraint(
            "candidate_profile_id",
            "skill_id",
            name=op.f("uq_candidate_skills_candidate_profile_id"),
        ),
    )
    op.create_index(
        op.f("ix_candidate_skills_skill_id"), "candidate_skills", ["skill_id"], unique=False
    )
    op.create_table(
        "certifications",
        sa.Column("candidate_profile_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("issuer", sa.String(length=200), nullable=True),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("expiration_date", sa.Date(), nullable=True),
        sa.Column("credential_id", sa.String(length=200), nullable=True),
        sa.Column("credential_url", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "expiration_date IS NULL OR issue_date IS NULL OR expiration_date >= issue_date",
            name=op.f("ck_certifications_date_range"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_profile_id"],
            ["candidate_profiles.id"],
            name=op.f("fk_certifications_candidate_profile_id_candidate_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_certifications")),
    )
    op.create_index(
        op.f("ix_certifications_candidate_profile_id"),
        "certifications",
        ["candidate_profile_id"],
        unique=False,
    )
    op.create_table(
        "cover_letters",
        sa.Column("candidate_profile_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "verification_failed",
                "verified",
                "approved",
                "archived",
                name="documentstatus",
                native_enum=False,
                length=32,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "file_format",
            sa.Enum("pdf", "docx", name="documentformat", native_enum=False, length=32),
            nullable=True,
        ),
        sa.Column("storage_key", sa.Text(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ai_execution_log_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "file_format IN ('pdf', 'docx')", name=op.f("ck_cover_letters_file_format_enum")
        ),
        sa.CheckConstraint(
            "status <> 'approved' OR approved_at IS NOT NULL",
            name=op.f("ck_tailored_resumes_approved_has_timestamp"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'verification_failed', 'verified', 'approved', 'archived')",
            name=op.f("ck_cover_letters_status_enum"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_cover_letters_version_positive")),
        sa.ForeignKeyConstraint(
            ["ai_execution_log_id"],
            ["ai_execution_logs.id"],
            name=op.f("fk_cover_letters_ai_execution_log_id_ai_execution_logs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["candidate_profile_id"],
            ["candidate_profiles.id"],
            name=op.f("fk_cover_letters_candidate_profile_id_candidate_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], name=op.f("fk_cover_letters_job_id_jobs")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cover_letters")),
        sa.UniqueConstraint(
            "candidate_profile_id",
            "job_id",
            "version",
            name=op.f("uq_cover_letters_candidate_profile_id"),
        ),
    )
    op.create_index(
        op.f("ix_cover_letters_ai_execution_log_id"),
        "cover_letters",
        ["ai_execution_log_id"],
        unique=False,
    )
    op.create_index(op.f("ix_cover_letters_job_id"), "cover_letters", ["job_id"], unique=False)
    op.create_table(
        "educations",
        sa.Column("candidate_profile_id", sa.Uuid(), nullable=False),
        sa.Column("institution", sa.String(length=300), nullable=False),
        sa.Column("degree", sa.String(length=200), nullable=True),
        sa.Column(
            "degree_level",
            sa.Enum(
                "high_school",
                "certificate",
                "diploma",
                "associate",
                "bachelor",
                "master",
                "doctorate",
                "other",
                name="degreelevel",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("field_of_study", sa.String(length=200), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("gpa", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("gpa_scale", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "degree_level IN ('high_school', 'certificate', 'diploma', 'associate', 'bachelor', 'master', 'doctorate', 'other')",
            name=op.f("ck_educations_degree_level_enum"),
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR start_date IS NULL OR end_date >= start_date",
            name=op.f("ck_educations_date_range"),
        ),
        sa.CheckConstraint(
            "gpa >= 0 AND (gpa_scale IS NULL OR gpa <= gpa_scale)",
            name=op.f("ck_educations_gpa_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_profile_id"],
            ["candidate_profiles.id"],
            name=op.f("fk_educations_candidate_profile_id_candidate_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_educations")),
    )
    op.create_index(
        op.f("ix_educations_candidate_profile_id"),
        "educations",
        ["candidate_profile_id"],
        unique=False,
    )
    op.create_table(
        "job_matches",
        sa.Column("candidate_profile_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("semantic_score", sa.Float(), nullable=True),
        sa.Column("skill_score", sa.Float(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("scoring_version", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "overall_score >= 0 AND overall_score <= 1",
            name=op.f("ck_job_matches_overall_score_range"),
        ),
        sa.CheckConstraint(
            "semantic_score >= 0 AND semantic_score <= 1",
            name=op.f("ck_job_matches_semantic_score_range"),
        ),
        sa.CheckConstraint(
            "skill_score >= 0 AND skill_score <= 1", name=op.f("ck_job_matches_skill_score_range")
        ),
        sa.ForeignKeyConstraint(
            ["candidate_profile_id"],
            ["candidate_profiles.id"],
            name=op.f("fk_job_matches_candidate_profile_id_candidate_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_job_matches_job_id_jobs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_matches")),
        sa.UniqueConstraint(
            "candidate_profile_id", "job_id", name=op.f("uq_job_matches_candidate_profile_id")
        ),
    )
    op.create_index(op.f("ix_job_matches_job_id"), "job_matches", ["job_id"], unique=False)
    op.create_index(
        "ix_job_matches_profile_score",
        "job_matches",
        ["candidate_profile_id", "overall_score"],
        unique=False,
    )
    op.create_table(
        "job_requirements",
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column(
            "requirement_type",
            sa.Enum(
                "skill",
                "experience",
                "education",
                "certification",
                "language",
                "responsibility",
                "other",
                name="requirementtype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "importance",
            sa.Enum(
                "required", "preferred", name="requirementimportance", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=True),
        sa.Column("min_years", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("embedding", Vector(1024), nullable=True),
        sa.Column("embedding_model", sa.String(length=100), nullable=True),
        sa.CheckConstraint(
            "importance IN ('required', 'preferred')",
            name=op.f("ck_job_requirements_importance_enum"),
        ),
        sa.CheckConstraint(
            "requirement_type IN ('skill', 'experience', 'education', 'certification', 'language', 'responsibility', 'other')",
            name=op.f("ck_job_requirements_requirement_type_enum"),
        ),
        sa.CheckConstraint(
            "length(btrim(description)) > 0", name=op.f("ck_job_requirements_description_not_blank")
        ),
        sa.CheckConstraint(
            "min_years >= 0", name=op.f("ck_job_requirements_min_years_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_job_requirements_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("fk_job_requirements_skill_id_skills"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_requirements")),
    )
    op.create_index(
        "ix_job_requirements_embedding_hnsw",
        "job_requirements",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        op.f("ix_job_requirements_job_id"), "job_requirements", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_job_requirements_skill_id"), "job_requirements", ["skill_id"], unique=False
    )
    op.create_table(
        "projects",
        sa.Column("candidate_profile_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("role", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("project_url", sa.Text(), nullable=True),
        sa.Column("repository_url", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR start_date IS NULL OR end_date >= start_date",
            name=op.f("ck_projects_date_range"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_profile_id"],
            ["candidate_profiles.id"],
            name=op.f("fk_projects_candidate_profile_id_candidate_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
    )
    op.create_index(
        op.f("ix_projects_candidate_profile_id"), "projects", ["candidate_profile_id"], unique=False
    )
    op.create_table(
        "resumes",
        sa.Column("candidate_profile_id", sa.Uuid(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column(
            "file_format",
            sa.Enum("pdf", "docx", name="documentformat", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "parse_status",
            sa.Enum(
                "pending", "parsed", "failed", name="parsestatus", native_enum=False, length=32
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("parse_error", sa.Text(), nullable=True),
        sa.Column("parsed_text", sa.Text(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "file_format IN ('pdf', 'docx')", name=op.f("ck_resumes_file_format_enum")
        ),
        sa.CheckConstraint(
            "parse_status IN ('pending', 'parsed', 'failed')",
            name=op.f("ck_resumes_parse_status_enum"),
        ),
        sa.CheckConstraint("file_size_bytes > 0", name=op.f("ck_resumes_file_size_positive")),
        sa.ForeignKeyConstraint(
            ["candidate_profile_id"],
            ["candidate_profiles.id"],
            name=op.f("fk_resumes_candidate_profile_id_candidate_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_resumes")),
        sa.UniqueConstraint(
            "candidate_profile_id", "sha256", name=op.f("uq_resumes_candidate_profile_id")
        ),
    )
    op.create_index(
        "uq_resumes_primary_per_profile",
        "resumes",
        ["candidate_profile_id"],
        unique=True,
        postgresql_where=sa.text("is_primary"),
    )
    op.create_table(
        "work_experiences",
        sa.Column("candidate_profile_id", sa.Uuid(), nullable=False),
        sa.Column("company_name", sa.String(length=300), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column(
            "employment_type",
            sa.Enum(
                "full_time",
                "part_time",
                "internship",
                "contract",
                "freelance",
                "volunteer",
                "other",
                name="employmenttype",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("is_current", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "employment_type IN ('full_time', 'part_time', 'internship', 'contract', 'freelance', 'volunteer', 'other')",
            name=op.f("ck_work_experiences_employment_type_enum"),
        ),
        sa.CheckConstraint(
            "NOT (is_current AND end_date IS NOT NULL)",
            name=op.f("ck_work_experiences_current_has_no_end"),
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR start_date IS NULL OR end_date >= start_date",
            name=op.f("ck_work_experiences_date_range"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_profile_id"],
            ["candidate_profiles.id"],
            name=op.f("fk_work_experiences_candidate_profile_id_candidate_profiles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_experiences")),
    )
    op.create_index(
        op.f("ix_work_experiences_candidate_profile_id"),
        "work_experiences",
        ["candidate_profile_id"],
        unique=False,
    )
    op.create_table(
        "coursework",
        sa.Column("candidate_profile_id", sa.Uuid(), nullable=False),
        sa.Column("education_id", sa.Uuid(), nullable=True),
        sa.Column("course_name", sa.String(length=300), nullable=False),
        sa.Column("course_code", sa.String(length=50), nullable=True),
        sa.Column("term", sa.String(length=100), nullable=True),
        sa.Column("grade", sa.String(length=20), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_profile_id"],
            ["candidate_profiles.id"],
            name=op.f("fk_coursework_candidate_profile_id_candidate_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["education_id"],
            ["educations.id"],
            name=op.f("fk_coursework_education_id_educations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_coursework")),
    )
    op.create_index(
        op.f("ix_coursework_candidate_profile_id"),
        "coursework",
        ["candidate_profile_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_coursework_education_id"), "coursework", ["education_id"], unique=False
    )
    op.create_table(
        "skill_gaps",
        sa.Column("job_match_id", sa.Uuid(), nullable=False),
        sa.Column("job_requirement_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=True),
        sa.Column(
            "severity",
            sa.Enum(
                "blocking", "significant", "minor", name="gapseverity", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "severity IN ('blocking', 'significant', 'minor')",
            name=op.f("ck_skill_gaps_severity_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["job_match_id"],
            ["job_matches.id"],
            name=op.f("fk_skill_gaps_job_match_id_job_matches"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_requirement_id"],
            ["job_requirements.id"],
            name=op.f("fk_skill_gaps_job_requirement_id_job_requirements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("fk_skill_gaps_skill_id_skills"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill_gaps")),
        sa.UniqueConstraint(
            "job_match_id", "job_requirement_id", name=op.f("uq_skill_gaps_job_match_id")
        ),
    )
    op.create_index(
        op.f("ix_skill_gaps_job_requirement_id"), "skill_gaps", ["job_requirement_id"], unique=False
    )
    op.create_index(op.f("ix_skill_gaps_skill_id"), "skill_gaps", ["skill_id"], unique=False)
    op.create_table(
        "tailored_resumes",
        sa.Column("candidate_profile_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("base_resume_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "verification_failed",
                "verified",
                "approved",
                "archived",
                name="documentstatus",
                native_enum=False,
                length=32,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "file_format",
            sa.Enum("pdf", "docx", name="documentformat", native_enum=False, length=32),
            nullable=True,
        ),
        sa.Column("storage_key", sa.Text(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ai_execution_log_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "file_format IN ('pdf', 'docx')", name=op.f("ck_tailored_resumes_file_format_enum")
        ),
        sa.CheckConstraint(
            "status <> 'approved' OR approved_at IS NOT NULL",
            name=op.f("ck_tailored_resumes_approved_has_timestamp"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'verification_failed', 'verified', 'approved', 'archived')",
            name=op.f("ck_tailored_resumes_status_enum"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_tailored_resumes_version_positive")),
        sa.ForeignKeyConstraint(
            ["ai_execution_log_id"],
            ["ai_execution_logs.id"],
            name=op.f("fk_tailored_resumes_ai_execution_log_id_ai_execution_logs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["base_resume_id"],
            ["resumes.id"],
            name=op.f("fk_tailored_resumes_base_resume_id_resumes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["candidate_profile_id"],
            ["candidate_profiles.id"],
            name=op.f("fk_tailored_resumes_candidate_profile_id_candidate_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_tailored_resumes_job_id_jobs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tailored_resumes")),
        sa.UniqueConstraint(
            "candidate_profile_id",
            "job_id",
            "version",
            name=op.f("uq_tailored_resumes_candidate_profile_id"),
        ),
    )
    op.create_index(
        op.f("ix_tailored_resumes_ai_execution_log_id"),
        "tailored_resumes",
        ["ai_execution_log_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tailored_resumes_base_resume_id"),
        "tailored_resumes",
        ["base_resume_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tailored_resumes_job_id"), "tailored_resumes", ["job_id"], unique=False
    )
    op.create_table(
        "applications",
        sa.Column("candidate_profile_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=False),
        sa.Column("tailored_resume_id", sa.Uuid(), nullable=True),
        sa.Column("cover_letter_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "ready_for_review",
                "approved",
                "filling",
                "awaiting_submission",
                "submitted",
                "interviewing",
                "offer",
                "accepted",
                "rejected",
                "withdrawn",
                name="applicationstatus",
                native_enum=False,
                length=32,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("application_url", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'submitted' OR submitted_at IS NOT NULL",
            name=op.f("ck_applications_submitted_has_time"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'ready_for_review', 'approved', 'filling', 'awaiting_submission', 'submitted', 'interviewing', 'offer', 'accepted', 'rejected', 'withdrawn')",
            name=op.f("ck_applications_status_enum"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('approved', 'filling', 'awaiting_submission', 'submitted', 'interviewing', 'offer', 'accepted', 'rejected') OR approved_at IS NOT NULL",
            name=op.f("ck_applications_approval_required"),
        ),
        sa.CheckConstraint(
            "submitted_at IS NULL OR (approved_at IS NOT NULL AND submitted_at >= approved_at)",
            name=op.f("ck_applications_submitted_after_approval"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_profile_id"],
            ["candidate_profiles.id"],
            name=op.f("fk_applications_candidate_profile_id_candidate_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["cover_letter_id"],
            ["cover_letters.id"],
            name=op.f("fk_applications_cover_letter_id_cover_letters"),
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], name=op.f("fk_applications_job_id_jobs")),
        sa.ForeignKeyConstraint(
            ["tailored_resume_id"],
            ["tailored_resumes.id"],
            name=op.f("fk_applications_tailored_resume_id_tailored_resumes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applications")),
        sa.UniqueConstraint(
            "candidate_profile_id", "job_id", name=op.f("uq_applications_candidate_profile_id")
        ),
    )
    op.create_index(
        op.f("ix_applications_cover_letter_id"), "applications", ["cover_letter_id"], unique=False
    )
    op.create_index(op.f("ix_applications_job_id"), "applications", ["job_id"], unique=False)
    op.create_index(
        "ix_applications_profile_status",
        "applications",
        ["candidate_profile_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_applications_tailored_resume_id"),
        "applications",
        ["tailored_resume_id"],
        unique=False,
    )
    op.create_table(
        "candidate_evidence",
        sa.Column("candidate_profile_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "project",
                "work_experience",
                "education",
                "certification",
                "achievement",
                "coursework",
                "profile",
                name="evidencesourcetype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "origin",
            sa.Enum(
                "user_entered",
                "resume_extracted",
                name="evidenceorigin",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("work_experience_id", sa.Uuid(), nullable=True),
        sa.Column("education_id", sa.Uuid(), nullable=True),
        sa.Column("certification_id", sa.Uuid(), nullable=True),
        sa.Column("achievement_id", sa.Uuid(), nullable=True),
        sa.Column("coursework_id", sa.Uuid(), nullable=True),
        sa.Column("source_resume_id", sa.Uuid(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("embedding", Vector(1024), nullable=True),
        sa.Column("embedding_model", sa.String(length=100), nullable=True),
        sa.CheckConstraint(
            "(source_type = 'achievement') = (achievement_id IS NOT NULL)",
            name=op.f("ck_candidate_evidence_achievement_matches_type"),
        ),
        sa.CheckConstraint(
            "(source_type = 'certification') = (certification_id IS NOT NULL)",
            name=op.f("ck_candidate_evidence_certification_matches_type"),
        ),
        sa.CheckConstraint(
            "(source_type = 'coursework') = (coursework_id IS NOT NULL)",
            name=op.f("ck_candidate_evidence_coursework_matches_type"),
        ),
        sa.CheckConstraint(
            "(source_type = 'education') = (education_id IS NOT NULL)",
            name=op.f("ck_candidate_evidence_education_matches_type"),
        ),
        sa.CheckConstraint(
            "(source_type = 'project') = (project_id IS NOT NULL)",
            name=op.f("ck_candidate_evidence_project_matches_type"),
        ),
        sa.CheckConstraint(
            "(source_type = 'work_experience') = (work_experience_id IS NOT NULL)",
            name=op.f("ck_candidate_evidence_work_experience_matches_type"),
        ),
        sa.CheckConstraint(
            "origin IN ('user_entered', 'resume_extracted')",
            name=op.f("ck_candidate_evidence_origin_enum"),
        ),
        sa.CheckConstraint(
            "source_resume_id IS NULL OR origin = 'resume_extracted'",
            name=op.f("ck_candidate_evidence_source_resume_implies_extracted"),
        ),
        sa.CheckConstraint(
            "source_type IN ('project', 'work_experience', 'education', 'certification', 'achievement', 'coursework', 'profile')",
            name=op.f("ck_candidate_evidence_source_type_enum"),
        ),
        sa.CheckConstraint(
            "length(btrim(content)) > 0", name=op.f("ck_candidate_evidence_content_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["achievement_id"],
            ["achievements.id"],
            name=op.f("fk_candidate_evidence_achievement_id_achievements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["candidate_profile_id"],
            ["candidate_profiles.id"],
            name=op.f("fk_candidate_evidence_candidate_profile_id_candidate_profiles"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["certification_id"],
            ["certifications.id"],
            name=op.f("fk_candidate_evidence_certification_id_certifications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["coursework_id"],
            ["coursework.id"],
            name=op.f("fk_candidate_evidence_coursework_id_coursework"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["education_id"],
            ["educations.id"],
            name=op.f("fk_candidate_evidence_education_id_educations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_candidate_evidence_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["source_resume_id"],
            ["resumes.id"],
            name=op.f("fk_candidate_evidence_source_resume_id_resumes"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["work_experience_id"],
            ["work_experiences.id"],
            name=op.f("fk_candidate_evidence_work_experience_id_work_experiences"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_evidence")),
    )
    op.create_index(
        op.f("ix_candidate_evidence_achievement_id"),
        "candidate_evidence",
        ["achievement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_evidence_certification_id"),
        "candidate_evidence",
        ["certification_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_evidence_coursework_id"),
        "candidate_evidence",
        ["coursework_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_evidence_education_id"),
        "candidate_evidence",
        ["education_id"],
        unique=False,
    )
    op.create_index(
        "ix_candidate_evidence_embedding_hnsw",
        "candidate_evidence",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.create_index(
        "ix_candidate_evidence_profile_source",
        "candidate_evidence",
        ["candidate_profile_id", "source_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_evidence_project_id"), "candidate_evidence", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_candidate_evidence_source_resume_id"),
        "candidate_evidence",
        ["source_resume_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_candidate_evidence_work_experience_id"),
        "candidate_evidence",
        ["work_experience_id"],
        unique=False,
    )
    op.create_table(
        "generated_claims",
        sa.Column("tailored_resume_id", sa.Uuid(), nullable=True),
        sa.Column("cover_letter_id", sa.Uuid(), nullable=True),
        sa.Column("claim_text", sa.Text(), nullable=False),
        sa.Column("section", sa.String(length=50), nullable=True),
        sa.Column("position", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "verified",
                "unsupported",
                "removed",
                name="claimstatus",
                native_enum=False,
                length=32,
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'verified', 'unsupported', 'removed')",
            name=op.f("ck_generated_claims_status_enum"),
        ),
        sa.CheckConstraint(
            "length(btrim(claim_text)) > 0", name=op.f("ck_generated_claims_claim_text_not_blank")
        ),
        sa.CheckConstraint(
            "num_nonnulls(tailored_resume_id, cover_letter_id) = 1",
            name=op.f("ck_generated_claims_exactly_one_document"),
        ),
        sa.ForeignKeyConstraint(
            ["cover_letter_id"],
            ["cover_letters.id"],
            name=op.f("fk_generated_claims_cover_letter_id_cover_letters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tailored_resume_id"],
            ["tailored_resumes.id"],
            name=op.f("fk_generated_claims_tailored_resume_id_tailored_resumes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generated_claims")),
    )
    op.create_index(
        op.f("ix_generated_claims_cover_letter_id"),
        "generated_claims",
        ["cover_letter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_generated_claims_tailored_resume_id"),
        "generated_claims",
        ["tailored_resume_id"],
        unique=False,
    )
    op.create_table(
        "application_status_history",
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "draft",
                "ready_for_review",
                "approved",
                "filling",
                "awaiting_submission",
                "submitted",
                "interviewing",
                "offer",
                "accepted",
                "rejected",
                "withdrawn",
                name="applicationstatus",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "draft",
                "ready_for_review",
                "approved",
                "filling",
                "awaiting_submission",
                "submitted",
                "interviewing",
                "offer",
                "accepted",
                "rejected",
                "withdrawn",
                name="applicationstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "actor",
            sa.Enum(
                "user", "system", "automation", name="statusactor", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor IN ('user', 'system', 'automation')",
            name=op.f("ck_application_status_history_actor_enum"),
        ),
        sa.CheckConstraint(
            "from_status IN ('draft', 'ready_for_review', 'approved', 'filling', 'awaiting_submission', 'submitted', 'interviewing', 'offer', 'accepted', 'rejected', 'withdrawn')",
            name=op.f("ck_application_status_history_from_status_enum"),
        ),
        sa.CheckConstraint(
            "to_status IN ('draft', 'ready_for_review', 'approved', 'filling', 'awaiting_submission', 'submitted', 'interviewing', 'offer', 'accepted', 'rejected', 'withdrawn')",
            name=op.f("ck_application_status_history_to_status_enum"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_application_status_history_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_status_history")),
    )
    op.create_index(
        "ix_application_status_history_app_created",
        "application_status_history",
        ["application_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "candidate_evidence_skills",
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column("skill_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["candidate_evidence.id"],
            name=op.f("fk_candidate_evidence_skills_evidence_id_candidate_evidence"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("fk_candidate_evidence_skills_skill_id_skills"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "evidence_id", "skill_id", name=op.f("pk_candidate_evidence_skills")
        ),
    )
    op.create_index(
        op.f("ix_candidate_evidence_skills_skill_id"),
        "candidate_evidence_skills",
        ["skill_id"],
        unique=False,
    )
    op.create_table(
        "claim_verifications",
        sa.Column("generated_claim_id", sa.Uuid(), nullable=False),
        sa.Column(
            "verdict",
            sa.Enum(
                "supported",
                "partially_supported",
                "unsupported",
                "contradicted",
                name="verificationverdict",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "method",
            sa.Enum(
                "rule_based",
                "llm",
                "human",
                name="verificationmethod",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("ai_execution_log_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "method IN ('rule_based', 'llm', 'human')",
            name=op.f("ck_claim_verifications_method_enum"),
        ),
        sa.CheckConstraint(
            "verdict IN ('supported', 'partially_supported', 'unsupported', 'contradicted')",
            name=op.f("ck_claim_verifications_verdict_enum"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_claim_verifications_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["ai_execution_log_id"],
            ["ai_execution_logs.id"],
            name=op.f("fk_claim_verifications_ai_execution_log_id_ai_execution_logs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["generated_claim_id"],
            ["generated_claims.id"],
            name=op.f("fk_claim_verifications_generated_claim_id_generated_claims"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_claim_verifications")),
    )
    op.create_index(
        op.f("ix_claim_verifications_ai_execution_log_id"),
        "claim_verifications",
        ["ai_execution_log_id"],
        unique=False,
    )
    op.create_index(
        "ix_claim_verifications_claim_created",
        "claim_verifications",
        ["generated_claim_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "generated_claim_evidence",
        sa.Column("generated_claim_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["candidate_evidence.id"],
            name=op.f("fk_generated_claim_evidence_evidence_id_candidate_evidence"),
            deferrable=True,
            initially="DEFERRED",
        ),
        sa.ForeignKeyConstraint(
            ["generated_claim_id"],
            ["generated_claims.id"],
            name=op.f("fk_generated_claim_evidence_generated_claim_id_generated_claims"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "generated_claim_id", "evidence_id", name=op.f("pk_generated_claim_evidence")
        ),
    )
    op.create_index(
        op.f("ix_generated_claim_evidence_evidence_id"),
        "generated_claim_evidence",
        ["evidence_id"],
        unique=False,
    )
    op.create_table(
        "interviews",
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column(
            "interview_type",
            sa.Enum(
                "phone_screen",
                "technical",
                "behavioral",
                "take_home",
                "onsite",
                "panel",
                "other",
                name="interviewtype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "scheduled",
                "completed",
                "cancelled",
                "no_show",
                name="interviewstatus",
                native_enum=False,
                length=32,
            ),
            server_default="scheduled",
            nullable=False,
        ),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=True),
        sa.Column("location", sa.String(length=300), nullable=True),
        sa.Column("meeting_url", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "interview_type IN ('phone_screen', 'technical', 'behavioral', 'take_home', 'onsite', 'panel', 'other')",
            name=op.f("ck_interviews_interview_type_enum"),
        ),
        sa.CheckConstraint(
            "status IN ('scheduled', 'completed', 'cancelled', 'no_show')",
            name=op.f("ck_interviews_status_enum"),
        ),
        sa.CheckConstraint("duration_minutes > 0", name=op.f("ck_interviews_duration_positive")),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_interviews_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interviews")),
    )
    op.create_index(
        op.f("ix_interviews_application_id"), "interviews", ["application_id"], unique=False
    )
    op.create_index(
        op.f("ix_interviews_scheduled_at"), "interviews", ["scheduled_at"], unique=False
    )
    op.create_table(
        "follow_ups",
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("interview_id", sa.Uuid(), nullable=True),
        sa.Column(
            "channel",
            sa.Enum(
                "email",
                "phone",
                "linkedin",
                "other",
                name="followupchannel",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "done", "skipped", name="followupstatus", native_enum=False, length=32
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("subject", sa.String(length=300), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "channel IN ('email', 'phone', 'linkedin', 'other')",
            name=op.f("ck_follow_ups_channel_enum"),
        ),
        sa.CheckConstraint(
            "status <> 'done' OR completed_at IS NOT NULL",
            name=op.f("ck_follow_ups_done_has_timestamp"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'done', 'skipped')", name=op.f("ck_follow_ups_status_enum")
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_follow_ups_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["interview_id"],
            ["interviews.id"],
            name=op.f("fk_follow_ups_interview_id_interviews"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_follow_ups")),
    )
    op.create_index(
        op.f("ix_follow_ups_application_id"), "follow_ups", ["application_id"], unique=False
    )
    op.create_index(
        op.f("ix_follow_ups_interview_id"), "follow_ups", ["interview_id"], unique=False
    )
    op.create_index("ix_follow_ups_status_due", "follow_ups", ["status", "due_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_follow_ups_status_due", table_name="follow_ups")
    op.drop_index(op.f("ix_follow_ups_interview_id"), table_name="follow_ups")
    op.drop_index(op.f("ix_follow_ups_application_id"), table_name="follow_ups")
    op.drop_table("follow_ups")
    op.drop_index(op.f("ix_interviews_scheduled_at"), table_name="interviews")
    op.drop_index(op.f("ix_interviews_application_id"), table_name="interviews")
    op.drop_table("interviews")
    op.drop_index(
        op.f("ix_generated_claim_evidence_evidence_id"), table_name="generated_claim_evidence"
    )
    op.drop_table("generated_claim_evidence")
    op.drop_index("ix_claim_verifications_claim_created", table_name="claim_verifications")
    op.drop_index(
        op.f("ix_claim_verifications_ai_execution_log_id"), table_name="claim_verifications"
    )
    op.drop_table("claim_verifications")
    op.drop_index(
        op.f("ix_candidate_evidence_skills_skill_id"), table_name="candidate_evidence_skills"
    )
    op.drop_table("candidate_evidence_skills")
    op.drop_index(
        "ix_application_status_history_app_created", table_name="application_status_history"
    )
    op.drop_table("application_status_history")
    op.drop_index(op.f("ix_generated_claims_tailored_resume_id"), table_name="generated_claims")
    op.drop_index(op.f("ix_generated_claims_cover_letter_id"), table_name="generated_claims")
    op.drop_table("generated_claims")
    op.drop_index(op.f("ix_candidate_evidence_work_experience_id"), table_name="candidate_evidence")
    op.drop_index(op.f("ix_candidate_evidence_source_resume_id"), table_name="candidate_evidence")
    op.drop_index(op.f("ix_candidate_evidence_project_id"), table_name="candidate_evidence")
    op.drop_index("ix_candidate_evidence_profile_source", table_name="candidate_evidence")
    op.drop_index(
        "ix_candidate_evidence_embedding_hnsw",
        table_name="candidate_evidence",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(op.f("ix_candidate_evidence_education_id"), table_name="candidate_evidence")
    op.drop_index(op.f("ix_candidate_evidence_coursework_id"), table_name="candidate_evidence")
    op.drop_index(op.f("ix_candidate_evidence_certification_id"), table_name="candidate_evidence")
    op.drop_index(op.f("ix_candidate_evidence_achievement_id"), table_name="candidate_evidence")
    op.drop_table("candidate_evidence")
    op.drop_index(op.f("ix_applications_tailored_resume_id"), table_name="applications")
    op.drop_index("ix_applications_profile_status", table_name="applications")
    op.drop_index(op.f("ix_applications_job_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_cover_letter_id"), table_name="applications")
    op.drop_table("applications")
    op.drop_index(op.f("ix_tailored_resumes_job_id"), table_name="tailored_resumes")
    op.drop_index(op.f("ix_tailored_resumes_base_resume_id"), table_name="tailored_resumes")
    op.drop_index(op.f("ix_tailored_resumes_ai_execution_log_id"), table_name="tailored_resumes")
    op.drop_table("tailored_resumes")
    op.drop_index(op.f("ix_skill_gaps_skill_id"), table_name="skill_gaps")
    op.drop_index(op.f("ix_skill_gaps_job_requirement_id"), table_name="skill_gaps")
    op.drop_table("skill_gaps")
    op.drop_index(op.f("ix_coursework_education_id"), table_name="coursework")
    op.drop_index(op.f("ix_coursework_candidate_profile_id"), table_name="coursework")
    op.drop_table("coursework")
    op.drop_index(op.f("ix_work_experiences_candidate_profile_id"), table_name="work_experiences")
    op.drop_table("work_experiences")
    op.drop_index(
        "uq_resumes_primary_per_profile",
        table_name="resumes",
        postgresql_where=sa.text("is_primary"),
    )
    op.drop_table("resumes")
    op.drop_index(op.f("ix_projects_candidate_profile_id"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_job_requirements_skill_id"), table_name="job_requirements")
    op.drop_index(op.f("ix_job_requirements_job_id"), table_name="job_requirements")
    op.drop_index(
        "ix_job_requirements_embedding_hnsw",
        table_name="job_requirements",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_table("job_requirements")
    op.drop_index("ix_job_matches_profile_score", table_name="job_matches")
    op.drop_index(op.f("ix_job_matches_job_id"), table_name="job_matches")
    op.drop_table("job_matches")
    op.drop_index(op.f("ix_educations_candidate_profile_id"), table_name="educations")
    op.drop_table("educations")
    op.drop_index(op.f("ix_cover_letters_job_id"), table_name="cover_letters")
    op.drop_index(op.f("ix_cover_letters_ai_execution_log_id"), table_name="cover_letters")
    op.drop_table("cover_letters")
    op.drop_index(op.f("ix_certifications_candidate_profile_id"), table_name="certifications")
    op.drop_table("certifications")
    op.drop_index(op.f("ix_candidate_skills_skill_id"), table_name="candidate_skills")
    op.drop_table("candidate_skills")
    op.drop_index(op.f("ix_achievements_candidate_profile_id"), table_name="achievements")
    op.drop_table("achievements")
    op.drop_index(
        "ix_jobs_embedding_hnsw",
        table_name="jobs",
        postgresql_using="hnsw",
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_index(op.f("ix_jobs_created_by_user_id"), table_name="jobs")
    op.drop_index("ix_jobs_active_posted", table_name="jobs")
    op.drop_table("jobs")
    op.drop_table("candidate_profiles")
    op.drop_index("ix_ai_execution_logs_user_created", table_name="ai_execution_logs")
    op.drop_index("ix_ai_execution_logs_operation_created", table_name="ai_execution_logs")
    op.drop_table("ai_execution_logs")
    op.drop_table("users")
    op.drop_table("skills")
    # ### end Alembic commands ###
