"""Job discovery: imported postings are unique per user; discovered input method.

Revision ID: 0012
Revises: 0011
Create Date: 2026-09-30 17:32:46.147017
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_jobs_source"), "jobs", type_="unique")
    op.create_unique_constraint(
        op.f("uq_jobs_created_by_user_id"),
        "jobs",
        ["created_by_user_id", "source", "source_name", "external_id"],
    )
    # ### end Alembic commands ###
    # --- Hand-written: autogenerate doesn't compare CHECK constraints. ---
    op.drop_constraint(op.f("ck_jobs_input_method_enum"), "jobs", "check")
    op.create_check_constraint(
        op.f("ck_jobs_input_method_enum"),
        "jobs",
        "input_method IN ('pasted_text', 'manual_entry', 'discovered')",
    )


def downgrade() -> None:
    # --- Hand-written (reverse of the CHECK change above). ---
    op.execute("UPDATE jobs SET input_method = 'pasted_text' WHERE input_method = 'discovered'")
    op.drop_constraint(op.f("ck_jobs_input_method_enum"), "jobs", "check")
    op.create_check_constraint(
        op.f("ck_jobs_input_method_enum"),
        "jobs",
        "input_method IN ('pasted_text', 'manual_entry')",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_jobs_created_by_user_id"), "jobs", type_="unique")
    op.create_unique_constraint(
        op.f("uq_jobs_source"),
        "jobs",
        ["source", "source_name", "external_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
