"""Verification reports: one stored report per verification run.

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-30 15:51:28.316144
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_reports",
        sa.Column("tailored_resume_id", sa.Uuid(), nullable=True),
        sa.Column("cover_letter_id", sa.Uuid(), nullable=True),
        sa.Column(
            "trigger",
            sa.Enum(
                "generation",
                "edit",
                "manual",
                name="verificationtrigger",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.Enum(
                "approved", "rejected", name="verificationoutcome", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("verifier", sa.String(length=100), nullable=False),
        sa.Column("report", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ai_execution_log_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IN ('approved', 'rejected')", name=op.f("ck_verification_reports_outcome_enum")
        ),
        sa.CheckConstraint(
            "trigger IN ('generation', 'edit', 'manual')",
            name=op.f("ck_verification_reports_trigger_enum"),
        ),
        sa.CheckConstraint(
            "num_nonnulls(tailored_resume_id, cover_letter_id) = 1",
            name=op.f("ck_verification_reports_exactly_one_document"),
        ),
        sa.ForeignKeyConstraint(
            ["ai_execution_log_id"],
            ["ai_execution_logs.id"],
            name=op.f("fk_verification_reports_ai_execution_log_id_ai_execution_logs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["cover_letter_id"],
            ["cover_letters.id"],
            name=op.f("fk_verification_reports_cover_letter_id_cover_letters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tailored_resume_id"],
            ["tailored_resumes.id"],
            name=op.f("fk_verification_reports_tailored_resume_id_tailored_resumes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_verification_reports")),
    )
    op.create_index(
        op.f("ix_verification_reports_ai_execution_log_id"),
        "verification_reports",
        ["ai_execution_log_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_reports_cover_letter_id"),
        "verification_reports",
        ["cover_letter_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_verification_reports_tailored_resume_id"),
        "verification_reports",
        ["tailored_resume_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_verification_reports_tailored_resume_id"), table_name="verification_reports"
    )
    op.drop_index(
        op.f("ix_verification_reports_cover_letter_id"), table_name="verification_reports"
    )
    op.drop_index(
        op.f("ix_verification_reports_ai_execution_log_id"), table_name="verification_reports"
    )
    op.drop_table("verification_reports")
    # ### end Alembic commands ###
