"""Tailored resume provenance: generator name and notes.

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-30 14:48:18.904324
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tailored_resumes", sa.Column("generator_name", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "tailored_resumes",
        sa.Column(
            "notes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tailored_resumes", "notes")
    op.drop_column("tailored_resumes", "generator_name")
    # ### end Alembic commands ###
